// flow-typed signature: 2438dffa58d7abd847ecbc4167cd9e77
// flow-typed version: <<STUB>>/eslint-plugin-immutable_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'eslint-plugin-immutable/index' {
  declare module.exports: $Exports<'eslint-plugin-immutable'>;
}
declare module 'eslint-plugin-immutable/index.js' {
  declare module.exports: $Exports<'eslint-plugin-immutable'>;
}
