// flow-typed signature: f374f9c775a5ab70147516e18feb01c5
// flow-typed version: <<STUB>>/@webpack-blocks/babel6_v^0.4.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webpack-blocks/babel6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@webpack-blocks/babel6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@webpack-blocks/babel6/index' {
  declare module.exports: $Exports<'@webpack-blocks/babel6'>;
}
declare module '@webpack-blocks/babel6/index.js' {
  declare module.exports: $Exports<'@webpack-blocks/babel6'>;
}
