// flow-typed signature: 40af8c706d4c6ad8bed5cc207c4af3a7
// flow-typed version: <<STUB>>/@webpack-blocks/extract-text2_v^0.4.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webpack-blocks/extract-text2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@webpack-blocks/extract-text2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@webpack-blocks/extract-text2/index' {
  declare module.exports: $Exports<'@webpack-blocks/extract-text2'>;
}
declare module '@webpack-blocks/extract-text2/index.js' {
  declare module.exports: $Exports<'@webpack-blocks/extract-text2'>;
}
